import type {
  Chain,
  Token,
  Transaction,
  BlockedToken,
  BlockedSite,
  SecurityEvent,
  DAppInfo,
  WalletState,
} from './types'

// ============ Supported chains (auto-connected, no manual config) ============

export const CHAINS: Chain[] = [
  {
    id: 'ethereum',
    name: 'Ethereum',
    symbol: 'ETH',
    shortLabel: 'ETH',
    color: '#627EEA',
    isEvm: true,
    rpcLabel: 'mainnet.infura.io (auto)',
    glyph: 'Ξ',
  },
  {
    id: 'bsc',
    name: 'BNB Smart Chain',
    symbol: 'BNB',
    shortLabel: 'BSC',
    color: '#F0B90B',
    isEvm: true,
    rpcLabel: 'bsc-dataseed.binance.org (auto)',
    glyph: 'B',
  },
  {
    id: 'polygon',
    name: 'Polygon PoS',
    symbol: 'MATIC',
    shortLabel: 'MATIC',
    color: '#8247E5',
    isEvm: true,
    rpcLabel: 'polygon-rpc.com (auto)',
    glyph: '⬡',
  },
  {
    id: 'arbitrum',
    name: 'Arbitrum One',
    symbol: 'ETH',
    shortLabel: 'ARB',
    color: '#28A0F0',
    isEvm: true,
    rpcLabel: 'arb1.arbitrum.io (auto)',
    glyph: 'A',
  },
  {
    id: 'optimism',
    name: 'Optimism',
    symbol: 'ETH',
    shortLabel: 'OP',
    color: '#FF0420',
    isEvm: true,
    rpcLabel: 'mainnet.optimism.io (auto)',
    glyph: 'O',
  },
  {
    id: 'avalanche',
    name: 'Avalanche C-Chain',
    symbol: 'AVAX',
    shortLabel: 'AVAX',
    color: '#E84142',
    isEvm: true,
    rpcLabel: 'api.avax.network (auto)',
    glyph: '▲',
  },
  {
    id: 'base',
    name: 'Base',
    symbol: 'ETH',
    shortLabel: 'BASE',
    color: '#0052FF',
    isEvm: true,
    rpcLabel: 'mainnet.base.org (auto)',
    glyph: 'Ⓑ',
  },
  {
    id: 'solana',
    name: 'Solana',
    symbol: 'SOL',
    shortLabel: 'SOL',
    color: '#14F195',
    isEvm: false,
    rpcLabel: 'api.mainnet-beta.solana.com (auto)',
    glyph: '◎',
  },
  {
    id: 'bitcoin',
    name: 'Bitcoin',
    symbol: 'BTC',
    shortLabel: 'BTC',
    color: '#F7931A',
    isEvm: false,
    rpcLabel: 'electrum.blockstream.info (SPV)',
    glyph: '₿',
  },
  {
    id: 'lightning',
    name: 'Lightning Network',
    symbol: 'sats',
    shortLabel: 'LN',
    color: '#F7A500',
    isEvm: false,
    rpcLabel: 'lnd Autonomous node (auto)',
    glyph: '⚡',
  },
]

export const chainById = (id: string): Chain =>
  CHAINS.find((c) => c.id === id) ?? CHAINS[0]

// ============ Initial tokens (verified, in hot wallet) ============

export const INITIAL_TOKENS: Token[] = [
  {
    id: 'eth-main',
    symbol: 'ETH',
    name: 'Ether',
    chain: 'ethereum',
    standard: 'native',
    balance: 3.4521,
    decimals: 18,
    priceUsd: 3245.67,
    change24h: 2.34,
    logoColor: '#627EEA',
    inVault: false,
    verified: true,
    risk: { level: 'safe', score: 98, reasons: ['Native asset', 'Verified contract'], blocked: false },
  },
  {
    id: 'usdc-eth',
    symbol: 'USDC',
    name: 'USD Coin',
    chain: 'ethereum',
    standard: 'ERC-20',
    balance: 4823.5,
    decimals: 6,
    priceUsd: 1.0,
    change24h: 0.01,
    contract: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    logoColor: '#2775CA',
    inVault: false,
    verified: true,
    risk: { level: 'safe', score: 99, reasons: ['Circle-issued', 'Audited contract', 'Top-5 market cap'], blocked: false },
  },
  {
    id: 'wbtc-eth',
    symbol: 'WBTC',
    name: 'Wrapped Bitcoin',
    chain: 'ethereum',
    standard: 'ERC-20',
    balance: 0.1245,
    decimals: 8,
    priceUsd: 62150.0,
    change24h: -0.87,
    contract: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    logoColor: '#F09242',
    inVault: false,
    verified: true,
    risk: { level: 'safe', score: 96, reasons: ['BitGo custody', 'Verified contract'], blocked: false },
  },
  {
    id: 'bnb-bsc',
    symbol: 'BNB',
    name: 'BNB',
    chain: 'bsc',
    standard: 'native',
    balance: 12.834,
    decimals: 18,
    priceUsd: 612.45,
    change24h: 1.12,
    logoColor: '#F0B90B',
    inVault: false,
    verified: true,
    risk: { level: 'safe', score: 95, reasons: ['Native asset'], blocked: false },
  },
  {
    id: 'matic-poly',
    symbol: 'MATIC',
    name: 'Polygon',
    chain: 'polygon',
    standard: 'native',
    balance: 4823.91,
    decimals: 18,
    priceUsd: 0.7823,
    change24h: -1.45,
    logoColor: '#8247E5',
    inVault: false,
    verified: true,
    risk: { level: 'safe', score: 95, reasons: ['Native asset'], blocked: false },
  },
  {
    id: 'sol-sol',
    symbol: 'SOL',
    name: 'Solana',
    chain: 'solana',
    standard: 'native',
    balance: 42.18,
    decimals: 9,
    priceUsd: 174.23,
    change24h: 4.56,
    logoColor: '#14F195',
    inVault: false,
    verified: true,
    risk: { level: 'safe', score: 97, reasons: ['Native asset'], blocked: false },
  },
  {
    id: 'btc-btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    chain: 'bitcoin',
    standard: 'native',
    balance: 0.3821,
    decimals: 8,
    priceUsd: 62150.0,
    change24h: -0.32,
    logoColor: '#F7931A',
    inVault: false,
    verified: true,
    risk: { level: 'safe', score: 99, reasons: ['Native BTC', 'UTXO model'], blocked: false },
  },
  {
    id: 'avax-avax',
    symbol: 'AVAX',
    name: 'Avalanche',
    chain: 'avalanche',
    standard: 'native',
    balance: 28.45,
    decimals: 18,
    priceUsd: 35.67,
    change24h: 2.89,
    logoColor: '#E84142',
    inVault: false,
    verified: true,
    risk: { level: 'safe', score: 94, reasons: ['Native asset'], blocked: false },
  },
]

// ============ Initial vault tokens (cold storage) ============

export const INITIAL_VAULT_TOKENS: Token[] = [
  {
    id: 'eth-vault',
    symbol: 'ETH',
    name: 'Ether (Vault)',
    chain: 'ethereum',
    standard: 'native',
    balance: 12.5,
    decimals: 18,
    priceUsd: 3245.67,
    change24h: 2.34,
    logoColor: '#627EEA',
    inVault: true,
    verified: true,
    risk: { level: 'safe', score: 99, reasons: ['Vault-locked', 'Cold storage'], blocked: false },
  },
  {
    id: 'wbtc-vault',
    symbol: 'WBTC',
    name: 'Wrapped Bitcoin (Vault)',
    chain: 'ethereum',
    standard: 'ERC-20',
    balance: 0.85,
    decimals: 8,
    priceUsd: 62150.0,
    change24h: -0.87,
    contract: '0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599',
    logoColor: '#F09242',
    inVault: true,
    verified: true,
    risk: { level: 'safe', score: 99, reasons: ['Vault-locked', 'Cold storage'], blocked: false },
  },
  {
    id: 'btc-vault',
    symbol: 'BTC',
    name: 'Bitcoin (Vault)',
    chain: 'bitcoin',
    standard: 'native',
    balance: 1.25,
    decimals: 8,
    priceUsd: 62150.0,
    change24h: -0.32,
    logoColor: '#F7931A',
    inVault: true,
    verified: true,
    risk: { level: 'safe', score: 99, reasons: ['Vault-locked', 'Cold storage', 'UTXO model'], blocked: false },
  },
]

// ============ Initial transactions ============

const now = Date.now()
export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'receive',
    tokenSymbol: 'ETH',
    amount: 1.2,
    usdValue: 3894.8,
    chain: 'ethereum',
    counterparty: '0x7a25...3bf1',
    timestamp: now - 1000 * 60 * 60 * 2,
    status: 'confirmed',
    risk: { level: 'safe', score: 95, reasons: ['Verified counterparty', 'No prior reports'], blocked: false },
    note: 'Verificação de integridade passou — origem limpa',
  },
  {
    id: 'tx-2',
    type: 'send',
    tokenSymbol: 'USDC',
    amount: 500,
    usdValue: 500,
    chain: 'ethereum',
    counterparty: '0x9b8c...d2e4',
    timestamp: now - 1000 * 60 * 60 * 6,
    status: 'confirmed',
    risk: { level: 'safe', score: 92, reasons: ['Address checked against blocklist', 'EOA destination'], blocked: false },
  },
  {
    id: 'tx-3',
    type: 'receive',
    tokenSymbol: 'SOL',
    amount: 5.0,
    usdValue: 871.15,
    chain: 'solana',
    counterparty: 'BmFp3...6kQz',
    timestamp: now - 1000 * 60 * 60 * 12,
    status: 'confirmed',
    risk: { level: 'low', score: 88, reasons: ['New counterparty', 'No malicious history detected'], blocked: false },
  },
  {
    id: 'tx-4',
    type: 'vault-move',
    tokenSymbol: 'BTC',
    amount: 0.5,
    usdValue: 31075,
    chain: 'bitcoin',
    counterparty: 'Vault interno',
    timestamp: now - 1000 * 60 * 60 * 24,
    status: 'confirmed',
    risk: { level: 'safe', score: 99, reasons: ['Internal vault transfer'], blocked: false },
    note: 'Movido para cofre — cold storage',
  },
  {
    id: 'tx-5',
    type: 'receive',
    tokenSymbol: '???',
    amount: 1000000,
    usdValue: 0,
    chain: 'bsc',
    counterparty: '0x4f2a...c891',
    timestamp: now - 1000 * 60 * 30,
    status: 'blocked',
    risk: {
      level: 'blocked',
      score: 5,
      reasons: [
        'Token na blocklist — honeypot conhecido',
        'Contrato não verificado no BscScan',
        'Liquidez extremamente baixa ($42)',
        'Padrão de transações de wash trading detectado',
      ],
      blocked: true,
    },
    note: 'Recebimento bloqueado automaticamente',
  },
]

// ============ Blocked tokens (historical blocklist) ============

export const INITIAL_BLOCKED_TOKENS: BlockedToken[] = [
  {
    id: 'bt-1',
    symbol: 'USDC-FAKE',
    name: 'USD Coin Fake',
    chain: 'bsc',
    contract: '0x4f2a9c2b3e1d4a5f6b7c8d9e0f1a2b3c4d5e6f70',
    reason: 'Honeypot — função de transferência bloqueia saída',
    blockedAt: now - 1000 * 60 * 30,
    source: 'auto',
  },
  {
    id: 'bt-2',
    symbol: 'SAFEMOON2',
    name: 'SafeMoon 2.0',
    chain: 'ethereum',
    contract: '0x8a1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d',
    reason: 'Taxa de 99% ao vender — padrão de rug pull',
    blockedAt: now - 1000 * 60 * 60 * 5,
    source: 'community',
  },
  {
    id: 'bt-3',
    symbol: 'ELONMARS',
    name: 'ElonMars Inu',
    chain: 'polygon',
    contract: '0x2b3c4d5e6f7081920a3b4c5d6e7f8091a2b3c4d5',
    reason: 'Mint authority não revogada — supply infinito',
    blockedAt: now - 1000 * 60 * 60 * 18,
    source: 'auto',
  },
  {
    id: 'bt-4',
    symbol: 'AIRDROP-X',
    name: 'Free Airdrop X',
    chain: 'arbitrum',
    contract: '0x5e6f7081920a3b4c5d6e7f8091a2b3c4d5e6f708',
    reason: 'Phishing via assinatura — drainer de permissões',
    blockedAt: now - 1000 * 60 * 60 * 36,
    source: 'community',
  },
  {
    id: 'bt-5',
    symbol: 'BSC-RUG',
    name: 'BSC Rugged Token',
    chain: 'bsc',
    contract: '0x192a3b4c5d6e7f8091a2b3c4d5e6f7081920a3b4',
    reason: 'Liquidez removida pelo deployer',
    blockedAt: now - 1000 * 60 * 60 * 48,
    source: 'auto',
  },
]

// ============ Blocked sites (DApp scam database) ============

export const INITIAL_BLOCKED_SITES: BlockedSite[] = [
  {
    id: 'bs-1',
    url: 'metarnask-login.com',
    reason: 'Phishing de MetaMask — captura seed phrase',
    blockedAt: now - 1000 * 60 * 60 * 24,
    category: 'phishing',
  },
  {
    id: 'bs-2',
    url: 'uniswap-airdrop.pro',
    reason: 'Drainer de tokens — imita Uniswap',
    blockedAt: now - 1000 * 60 * 60 * 36,
    category: 'drainer',
  },
  {
    id: 'bs-3',
    url: 'opensea-mint-free.io',
    reason: 'Falso mint NFT — roubo de carteira',
    blockedAt: now - 1000 * 60 * 60 * 48,
    category: 'fake-dapp',
  },
  {
    id: 'bs-4',
    url: 'wallet-connect-restore.app',
    reason: 'Malware — falso WalletConnect',
    blockedAt: now - 1000 * 60 * 60 * 60,
    category: 'malware',
  },
  {
    id: 'bs-5',
    url: 'aave-v3-bonus.com',
    reason: 'Phishing de Aave — captura assinatura',
    blockedAt: now - 1000 * 60 * 60 * 72,
    category: 'phishing',
  },
]

// ============ Security events ============

export const INITIAL_SECURITY_EVENTS: SecurityEvent[] = [
  {
    id: 'se-1',
    type: 'blocked-token',
    title: 'Token malicioso bloqueado',
    description: 'Recebimento de USDC-FAKE na BSC foi bloqueado automaticamente (honeypot).',
    timestamp: now - 1000 * 60 * 30,
    severity: 'critical',
    related: 'USDC-FAKE',
  },
  {
    id: 'se-2',
    type: 'blocked-site',
    title: 'Site malicioso bloqueado',
    description: 'metarnask-login.com foi bloqueado antes da conexão DApp.',
    timestamp: now - 1000 * 60 * 60 * 24,
    severity: 'critical',
    related: 'metarnask-login.com',
  },
  {
    id: 'se-3',
    type: 'suspicious-tx',
    title: 'Transação suspeita simulada',
    description: 'Simulação detectou drenagem de 100% do saldo — bloqueada na Sessão Segura.',
    timestamp: now - 1000 * 60 * 60 * 20,
    severity: 'warning',
  },
  {
    id: 'se-4',
    type: 'vault-access',
    title: 'Acesso ao cofre',
    description: 'Cofre desbloqueado via biometria + PIN — sessão de 5 min.',
    timestamp: now - 1000 * 60 * 60 * 24 * 2,
    severity: 'info',
  },
  {
    id: 'se-5',
    type: 'high-risk-warning',
    title: 'Endereço marcado como alto risco',
    description: 'Endereço de destino 0x3f...c4d listado em 3 relatórios de comunidade.',
    timestamp: now - 1000 * 60 * 60 * 24 * 3,
    severity: 'warning',
  },
]

// ============ DApp catalog (verified) ============

export const DAPPS: DAppInfo[] = [
  {
    id: 'dapp-1',
    name: 'Uniswap V3',
    url: 'app.uniswap.org',
    category: 'DEX',
    rating: 'verified',
    description: 'Principal DEX da Ethereum — swaps e liquidez.',
  },
  {
    id: 'dapp-2',
    name: 'Aave V3',
    url: 'app.aave.com',
    category: 'DeFi',
    rating: 'verified',
    description: 'Plataforma de empréstimo e rendimentos.',
  },
  {
    id: 'dapp-3',
    name: 'OpenSea',
    url: 'opensea.io',
    category: 'NFT',
    rating: 'verified',
    description: 'Marketplace de NFTs multi-cadeia.',
  },
  {
    id: 'dapp-4',
    name: 'Lido',
    url: 'lido.fi',
    category: 'Staking',
    rating: 'verified',
    description: 'Liquid staking de ETH e SOL.',
  },
  {
    id: 'dapp-5',
    name: 'Jupiter',
    url: 'jup.ag',
    category: 'DEX',
    rating: 'verified',
    description: 'Agregador de swaps na Solana.',
  },
]

// ============ Initial wallet state ============

export const INITIAL_WALLET_STATE: WalletState = {
  address: '0x7F3aB2c9D4e5F678901a2B3c4D5e6F7081920a3B',
  tokens: INITIAL_TOKENS,
  vaultTokens: INITIAL_VAULT_TOKENS,
  transactions: INITIAL_TRANSACTIONS,
  blockedTokens: INITIAL_BLOCKED_TOKENS,
  blockedSites: INITIAL_BLOCKED_SITES,
  securityEvents: INITIAL_SECURITY_EVENTS,
  vaultUnlocked: false,
  safeSessionActive: false,
  globalRiskScore: 87,
}
